version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - clickhouse
        environment:
            - CLICKHOUSE_HOST=clickhouse
        env_file:
            - .env

    clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - ./migrations:/docker-entrypoint-initdb.d
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

volumes:
    clickhouse_data:
